// Full set of 118 elements (basic properties). Lanthanides placed on period 8, actinides on period 9
const ELEMENTS = [
  { number: 1, symbol: 'H', name: 'Hydrogen', group: 1, period: 1, mass: 1.008, category: 'nonmetal' },
  { number: 2, symbol: 'He', name: 'Helium', group: 18, period: 1, mass: 4.0026, category: 'noble gas' },
  { number: 3, symbol: 'Li', name: 'Lithium', group: 1, period: 2, mass: 6.94, category: 'alkali metal' },
  { number: 4, symbol: 'Be', name: 'Beryllium', group: 2, period: 2, mass: 9.0122, category: 'alkaline earth metal' },
  { number: 5, symbol: 'B', name: 'Boron', group: 13, period: 2, mass: 10.81, category: 'metalloid' },
  { number: 6, symbol: 'C', name: 'Carbon', group: 14, period: 2, mass: 12.011, category: 'nonmetal' },
  { number: 7, symbol: 'N', name: 'Nitrogen', group: 15, period: 2, mass: 14.007, category: 'nonmetal' },
  { number: 8, symbol: 'O', name: 'Oxygen', group: 16, period: 2, mass: 15.999, category: 'nonmetal' },
  { number: 9, symbol: 'F', name: 'Fluorine', group: 17, period: 2, mass: 18.998, category: 'halogen' },
  { number: 10, symbol: 'Ne', name: 'Neon', group: 18, period: 2, mass: 20.180, category: 'noble gas' },

  { number: 11, symbol: 'Na', name: 'Sodium', group: 1, period: 3, mass: 22.990, category: 'alkali metal' },
  { number: 12, symbol: 'Mg', name: 'Magnesium', group: 2, period: 3, mass: 24.305, category: 'alkaline earth metal' },
  { number: 13, symbol: 'Al', name: 'Aluminium', group: 13, period: 3, mass: 26.982, category: 'post-transition metal' },
  { number: 14, symbol: 'Si', name: 'Silicon', group: 14, period: 3, mass: 28.085, category: 'metalloid' },
  { number: 15, symbol: 'P', name: 'Phosphorus', group: 15, period: 3, mass: 30.974, category: 'nonmetal' },
  { number: 16, symbol: 'S', name: 'Sulfur', group: 16, period: 3, mass: 32.06, category: 'nonmetal' },
  { number: 17, symbol: 'Cl', name: 'Chlorine', group: 17, period: 3, mass: 35.45, category: 'halogen' },
  { number: 18, symbol: 'Ar', name: 'Argon', group: 18, period: 3, mass: 39.948, category: 'noble gas' },

  { number: 19, symbol: 'K', name: 'Potassium', group: 1, period: 4, mass: 39.098, category: 'alkali metal' },
  { number: 20, symbol: 'Ca', name: 'Calcium', group: 2, period: 4, mass: 40.078, category: 'alkaline earth metal' },
  { number: 21, symbol: 'Sc', name: 'Scandium', group: 3, period: 4, mass: 44.956, category: 'transition metal' },
  { number: 22, symbol: 'Ti', name: 'Titanium', group: 4, period: 4, mass: 47.867, category: 'transition metal' },
  { number: 23, symbol: 'V', name: 'Vanadium', group: 5, period: 4, mass: 50.942, category: 'transition metal' },
  { number: 24, symbol: 'Cr', name: 'Chromium', group: 6, period: 4, mass: 51.996, category: 'transition metal' },
  { number: 25, symbol: 'Mn', name: 'Manganese', group: 7, period: 4, mass: 54.938, category: 'transition metal' },
  { number: 26, symbol: 'Fe', name: 'Iron', group: 8, period: 4, mass: 55.845, category: 'transition metal' },
  { number: 27, symbol: 'Co', name: 'Cobalt', group: 9, period: 4, mass: 58.933, category: 'transition metal' },
  { number: 28, symbol: 'Ni', name: 'Nickel', group: 10, period: 4, mass: 58.693, category: 'transition metal' },
  { number: 29, symbol: 'Cu', name: 'Copper', group: 11, period: 4, mass: 63.546, category: 'transition metal' },
  { number: 30, symbol: 'Zn', name: 'Zinc', group: 12, period: 4, mass: 65.38, category: 'transition metal' },
  { number: 31, symbol: 'Ga', name: 'Gallium', group: 13, period: 4, mass: 69.723, category: 'post-transition metal' },
  { number: 32, symbol: 'Ge', name: 'Germanium', group: 14, period: 4, mass: 72.630, category: 'metalloid' },
  { number: 33, symbol: 'As', name: 'Arsenic', group: 15, period: 4, mass: 74.922, category: 'metalloid' },
  { number: 34, symbol: 'Se', name: 'Selenium', group: 16, period: 4, mass: 78.971, category: 'nonmetal' },
  { number: 35, symbol: 'Br', name: 'Bromine', group: 17, period: 4, mass: 79.904, category: 'halogen' },
  { number: 36, symbol: 'Kr', name: 'Krypton', group: 18, period: 4, mass: 83.798, category: 'noble gas' },

  { number: 37, symbol: 'Rb', name: 'Rubidium', group: 1, period: 5, mass: 85.468, category: 'alkali metal' },
  { number: 38, symbol: 'Sr', name: 'Strontium', group: 2, period: 5, mass: 87.62, category: 'alkaline earth metal' },
  { number: 39, symbol: 'Y', name: 'Yttrium', group: 3, period: 5, mass: 88.906, category: 'transition metal' },
  { number: 40, symbol: 'Zr', name: 'Zirconium', group: 4, period: 5, mass: 91.224, category: 'transition metal' },
  { number: 41, symbol: 'Nb', name: 'Niobium', group: 5, period: 5, mass: 92.906, category: 'transition metal' },
  { number: 42, symbol: 'Mo', name: 'Molybdenum', group: 6, period: 5, mass: 95.95, category: 'transition metal' },
  { number: 43, symbol: 'Tc', name: 'Technetium', group: 7, period: 5, mass: 98, category: 'transition metal' },
  { number: 44, symbol: 'Ru', name: 'Ruthenium', group: 8, period: 5, mass: 101.07, category: 'transition metal' },
  { number: 45, symbol: 'Rh', name: 'Rhodium', group: 9, period: 5, mass: 102.91, category: 'transition metal' },
  { number: 46, symbol: 'Pd', name: 'Palladium', group: 10, period: 5, mass: 106.42, category: 'transition metal' },
  { number: 47, symbol: 'Ag', name: 'Silver', group: 11, period: 5, mass: 107.87, category: 'transition metal' },
  { number: 48, symbol: 'Cd', name: 'Cadmium', group: 12, period: 5, mass: 112.41, category: 'transition metal' },
  { number: 49, symbol: 'In', name: 'Indium', group: 13, period: 5, mass: 114.82, category: 'post-transition metal' },
  { number: 50, symbol: 'Sn', name: 'Tin', group: 14, period: 5, mass: 118.71, category: 'post-transition metal' },
  { number: 51, symbol: 'Sb', name: 'Antimony', group: 15, period: 5, mass: 121.76, category: 'metalloid' },
  { number: 52, symbol: 'Te', name: 'Tellurium', group: 16, period: 5, mass: 127.60, category: 'metalloid' },
  { number: 53, symbol: 'I', name: 'Iodine', group: 17, period: 5, mass: 126.90, category: 'halogen' },
  { number: 54, symbol: 'Xe', name: 'Xenon', group: 18, period: 5, mass: 131.29, category: 'noble gas' },

  { number: 55, symbol: 'Cs', name: 'Caesium', group: 1, period: 6, mass: 132.91, category: 'alkali metal' },
  { number: 56, symbol: 'Ba', name: 'Barium', group: 2, period: 6, mass: 137.33, category: 'alkaline earth metal' },
  // Lanthanides row (displayed on period 8)
  { number: 57, symbol: 'La', name: 'Lanthanum', group: 3, period: 8, mass: 138.91, category: 'lanthanoid' },
  { number: 58, symbol: 'Ce', name: 'Cerium', group: 4, period: 8, mass: 140.12, category: 'lanthanoid' },
  { number: 59, symbol: 'Pr', name: 'Praseodymium', group: 5, period: 8, mass: 140.91, category: 'lanthanoid' },
  { number: 60, symbol: 'Nd', name: 'Neodymium', group: 6, period: 8, mass: 144.24, category: 'lanthanoid' },
  { number: 61, symbol: 'Pm', name: 'Promethium', group: 7, period: 8, mass: 145, category: 'lanthanoid' },
  { number: 62, symbol: 'Sm', name: 'Samarium', group: 8, period: 8, mass: 150.36, category: 'lanthanoid' },
  { number: 63, symbol: 'Eu', name: 'Europium', group: 9, period: 8, mass: 151.96, category: 'lanthanoid' },
  { number: 64, symbol: 'Gd', name: 'Gadolinium', group: 10, period: 8, mass: 157.25, category: 'lanthanoid' },
  { number: 65, symbol: 'Tb', name: 'Terbium', group: 11, period: 8, mass: 158.93, category: 'lanthanoid' },
  { number: 66, symbol: 'Dy', name: 'Dysprosium', group: 12, period: 8, mass: 162.50, category: 'lanthanoid' },
  { number: 67, symbol: 'Ho', name: 'Holmium', group: 13, period: 8, mass: 164.93, category: 'lanthanoid' },
  { number: 68, symbol: 'Er', name: 'Erbium', group: 14, period: 8, mass: 167.26, category: 'lanthanoid' },
  { number: 69, symbol: 'Tm', name: 'Thulium', group: 15, period: 8, mass: 168.93, category: 'lanthanoid' },
  { number: 70, symbol: 'Yb', name: 'Ytterbium', group: 16, period: 8, mass: 173.05, category: 'lanthanoid' },
  { number: 71, symbol: 'Lu', name: 'Lutetium', group: 17, period: 8, mass: 174.97, category: 'lanthanoid' },

  { number: 72, symbol: 'Hf', name: 'Hafnium', group: 4, period: 6, mass: 178.49, category: 'transition metal' },
  { number: 73, symbol: 'Ta', name: 'Tantalum', group: 5, period: 6, mass: 180.95, category: 'transition metal' },
  { number: 74, symbol: 'W', name: 'Tungsten', group: 6, period: 6, mass: 183.84, category: 'transition metal' },
  { number: 75, symbol: 'Re', name: 'Rhenium', group: 7, period: 6, mass: 186.21, category: 'transition metal' },
  { number: 76, symbol: 'Os', name: 'Osmium', group: 8, period: 6, mass: 190.23, category: 'transition metal' },
  { number: 77, symbol: 'Ir', name: 'Iridium', group: 9, period: 6, mass: 192.22, category: 'transition metal' },
  { number: 78, symbol: 'Pt', name: 'Platinum', group: 10, period: 6, mass: 195.08, category: 'transition metal' },
  { number: 79, symbol: 'Au', name: 'Gold', group: 11, period: 6, mass: 196.97, category: 'transition metal' },
  { number: 80, symbol: 'Hg', name: 'Mercury', group: 12, period: 6, mass: 200.59, category: 'transition metal' },
  { number: 81, symbol: 'Tl', name: 'Thallium', group: 13, period: 6, mass: 204.38, category: 'post-transition metal' },
  { number: 82, symbol: 'Pb', name: 'Lead', group: 14, period: 6, mass: 207.2, category: 'post-transition metal' },
  { number: 83, symbol: 'Bi', name: 'Bismuth', group: 15, period: 6, mass: 208.98, category: 'post-transition metal' },
  { number: 84, symbol: 'Po', name: 'Polonium', group: 16, period: 6, mass: 209, category: 'metalloid' },
  { number: 85, symbol: 'At', name: 'Astatine', group: 17, period: 6, mass: 210, category: 'halogen' },
  { number: 86, symbol: 'Rn', name: 'Radon', group: 18, period: 6, mass: 222, category: 'noble gas' },

  { number: 87, symbol: 'Fr', name: 'Francium', group: 1, period: 7, mass: 223, category: 'alkali metal' },
  { number: 88, symbol: 'Ra', name: 'Radium', group: 2, period: 7, mass: 226, category: 'alkaline earth metal' },
  // Actinides row (displayed on period 9)
  { number: 89, symbol: 'Ac', name: 'Actinium', group: 3, period: 9, mass: 227, category: 'actinoid' },
  { number: 90, symbol: 'Th', name: 'Thorium', group: 4, period: 9, mass: 232.04, category: 'actinoid' },
  { number: 91, symbol: 'Pa', name: 'Protactinium', group: 5, period: 9, mass: 231.04, category: 'actinoid' },
  { number: 92, symbol: 'U', name: 'Uranium', group: 6, period: 9, mass: 238.03, category: 'actinoid' },
  { number: 93, symbol: 'Np', name: 'Neptunium', group: 7, period: 9, mass: 237, category: 'actinoid' },
  { number: 94, symbol: 'Pu', name: 'Plutonium', group: 8, period: 9, mass: 244, category: 'actinoid' },
  { number: 95, symbol: 'Am', name: 'Americium', group: 9, period: 9, mass: 243, category: 'actinoid' },
  { number: 96, symbol: 'Cm', name: 'Curium', group: 10, period: 9, mass: 247, category: 'actinoid' },
  { number: 97, symbol: 'Bk', name: 'Berkelium', group: 11, period: 9, mass: 247, category: 'actinoid' },
  { number: 98, symbol: 'Cf', name: 'Californium', group: 12, period: 9, mass: 251, category: 'actinoid' },
  { number: 99, symbol: 'Es', name: 'Einsteinium', group: 13, period: 9, mass: 252, category: 'actinoid' },
  { number: 100, symbol: 'Fm', name: 'Fermium', group: 14, period: 9, mass: 257, category: 'actinoid' },
  { number: 101, symbol: 'Md', name: 'Mendelevium', group: 15, period: 9, mass: 258, category: 'actinoid' },
  { number: 102, symbol: 'No', name: 'Nobelium', group: 16, period: 9, mass: 259, category: 'actinoid' },
  { number: 103, symbol: 'Lr', name: 'Lawrencium', group: 17, period: 9, mass: 266, category: 'actinoid' },

  { number: 104, symbol: 'Rf', name: 'Rutherfordium', group: 4, period: 7, mass: 267, category: 'transition metal' },
  { number: 105, symbol: 'Db', name: 'Dubnium', group: 5, period: 7, mass: 268, category: 'transition metal' },
  { number: 106, symbol: 'Sg', name: 'Seaborgium', group: 6, period: 7, mass: 269, category: 'transition metal' },
  { number: 107, symbol: 'Bh', name: 'Bohrium', group: 7, period: 7, mass: 270, category: 'transition metal' },
  { number: 108, symbol: 'Hs', name: 'Hassium', group: 8, period: 7, mass: 269, category: 'transition metal' },
  { number: 109, symbol: 'Mt', name: 'Meitnerium', group: 9, period: 7, mass: 278, category: 'unknown' },
  { number: 110, symbol: 'Ds', name: 'Darmstadtium', group: 10, period: 7, mass: 281, category: 'unknown' },
  { number: 111, symbol: 'Rg', name: 'Roentgenium', group: 11, period: 7, mass: 282, category: 'unknown' },
  { number: 112, symbol: 'Cn', name: 'Copernicium', group: 12, period: 7, mass: 285, category: 'post-transition metal' },
  { number: 113, symbol: 'Nh', name: 'Nihonium', group: 13, period: 7, mass: 286, category: 'post-transition metal' },
  { number: 114, symbol: 'Fl', name: 'Flerovium', group: 14, period: 7, mass: 289, category: 'post-transition metal' },
  { number: 115, symbol: 'Mc', name: 'Moscovium', group: 15, period: 7, mass: 288, category: 'post-transition metal' },
  { number: 116, symbol: 'Lv', name: 'Livermorium', group: 16, period: 7, mass: 293, category: 'post-transition metal' },
  { number: 117, symbol: 'Ts', name: 'Tennessine', group: 17, period: 7, mass: 294, category: 'halogen' },
  { number: 118, symbol: 'Og', name: 'Oganesson', group: 18, period: 7, mass: 294, category: 'noble gas' }
];

export { ELEMENTS };
